version: '3'
services:
  db:
    container_name: test-db
    image: postgis/postgis:12-3.1-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: dontchangeme
      POSTGRES_DB: debug_db
    ports:
      - "9432:5432"
